version: "3.5"

services:

  mysql:
    container_name: ${NAME}_database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    volumes:
      - ${DB_DATA}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${NAME}_phpmyadmin
    depends_on:
      - mysql
    networks:
      - backend
      - proxy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      VIRTUAL_HOST: pma.emil.moe
      LETSENCRYPT_HOST: pma.emil.moe
    restart: always

  apache:
    container_name: ${NAME}_web
    image: emilmoe/wordpress:latest
    depends_on:
      - mysql
    restart: always
    volumes:
      - ${WP_DATA}:/var/www/html
    networks:
      - backend
      - proxy
    environment:
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASS: ${DB_PASSWORD}
      DB_HOST: mysql
      WP_URL: ${WP_DOMAIN}
      WP_ADMIN: ${WP_USER}
      WP_ADMIN_EMAIL: ${WP_EMAIL}
      WP_ADMIN_PASS: ${WP_PASSWORD}
      VIRTUAL_HOST: ${WP_DOMAINS}
      LETSENCRYPT_HOST: ${WP_DOMAINS}

#  backup:

networks:
  backend:
    driver: bridge
  proxy:
    external: true
